src/gz openwrt_base https://mirrors.vsean.net/openwrt/releases/24.10-SNAPSHOT/targets/ipq806x/generic/packages/base/
src/gz openwrt_luci https://mirrors.vsean.net/openwrt/releases/24.10-SNAPSHOT/targets/ipq806x/generic/packages/luci/
src/gz openwrt_packages https://mirrors.vsean.net/openwrt/releases/24.10-SNAPSHOT/targets/ipq806x/generic/packages/packages
src/gz openwrt_routing https://mirrors.vsean.net/openwrt/releases/24.10-SNAPSHOT/targets/ipq806x/generic/packages/routing
src/gz openwrt_telephony https://mirrors.vsean.net/openwrt/releases/24.10-SNAPSHOT/targets/ipq806x/generic/packages/telephony
